server:
  port: ${port:9100}
  servlet:
    context-path: /MS_2
spring:
  application:
    name: ms-two
eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
 # instance:
 #    hostname: localhost
logging:
  level:
    #org.springframework: DEBUG
    com.mypoc: DEBUG
